/*
 * Copyright (c) 2023, the Pixnews project authors and contributors. Please see the AUTHORS file for details.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package ru.pixnews.foundation.ui.theme

import androidx.compose.ui.graphics.Color

public val md_theme_light_primary: Color = Color(0xFF4356B9)
public val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
public val md_theme_light_primaryContainer: Color = Color(0xFFDEE0FF)
public val md_theme_light_onPrimaryContainer: Color = Color(0xFF00105A)
public val md_theme_light_secondary: Color = Color(0xFF446813)
public val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
public val md_theme_light_secondaryContainer: Color = Color(0xFFC4F18C)
public val md_theme_light_onSecondaryContainer: Color = Color(0xFF102000)
public val md_theme_light_tertiary: Color = Color(0xFF5B6400)
public val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
public val md_theme_light_tertiaryContainer: Color = Color(0xFFDCED4E)
public val md_theme_light_onTertiaryContainer: Color = Color(0xFF1A1E00)
public val md_theme_light_error: Color = Color(0xFFBA1A1A)
public val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_light_onError: Color = Color(0xFFFFFFFF)
public val md_theme_light_onErrorContainer: Color = Color(0xFF410002)
public val md_theme_light_background: Color = Color(0xFFFFFBFF)
public val md_theme_light_onBackground: Color = Color(0xFF24005A)
public val md_theme_light_surface: Color = Color(0xFFFFFBFF)
public val md_theme_light_onSurface: Color = Color(0xFF24005A)
public val md_theme_light_surfaceVariant: Color = Color(0xFFE3E1EC)
public val md_theme_light_onSurfaceVariant: Color = Color(0xFF46464F)
public val md_theme_light_outline: Color = Color(0xFF767680)
public val md_theme_light_inverseOnSurface: Color = Color(0xFFF6EDFF)
public val md_theme_light_inverseSurface: Color = Color(0xFF3A1D71)
public val md_theme_light_inversePrimary: Color = Color(0xFFBAC3FF)
public val md_theme_light_shadow: Color = Color(0xFF000000)
public val md_theme_light_surfaceTint: Color = Color(0xFF4356B9)
public val md_theme_light_outlineVariant: Color = Color(0xFFC6C5D0)
public val md_theme_light_scrim: Color = Color(0xFF000000)

public val md_theme_palette_tertiary70: Color = Color(0xFFA5B40D)
public val md_theme_palette_primary30: Color = Color(0xFF283C9F)
public val md_theme_palette_primary95: Color = Color(0xFFF0EFFF)

public val md_theme_palette_neutral_variant_40: Color = Color(0xFF5D5E67)
public val md_theme_palette_neutral_variant_90: Color = Color(0xFFE3E1EC)
public val md_theme_palette_neutral_variant_95: Color = Color(0xFFF1EFFA)

public val md_theme_dark_primary: Color = Color(0xFFBAC3FF)
public val md_theme_dark_onPrimary: Color = Color(0xFF072289)
public val md_theme_dark_primaryContainer: Color = Color(0xFF283C9F)
public val md_theme_dark_onPrimaryContainer: Color = Color(0xFFDEE0FF)
public val md_theme_dark_secondary: Color = Color(0xFFA9D473)
public val md_theme_dark_onSecondary: Color = Color(0xFF1F3700)
public val md_theme_dark_secondaryContainer: Color = Color(0xFF304F00)
public val md_theme_dark_onSecondaryContainer: Color = Color(0xFFC4F18C)
public val md_theme_dark_tertiary: Color = Color(0xFFC0D032)
public val md_theme_dark_onTertiary: Color = Color(0xFF2E3300)
public val md_theme_dark_tertiaryContainer: Color = Color(0xFF444B00)
public val md_theme_dark_onTertiaryContainer: Color = Color(0xFFDCED4E)
public val md_theme_dark_error: Color = Color(0xFFFFB4AB)
public val md_theme_dark_errorContainer: Color = Color(0xFF93000A)
public val md_theme_dark_onError: Color = Color(0xFF690005)
public val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6)
public val md_theme_dark_background: Color = Color(0xFF24005A)
public val md_theme_dark_onBackground: Color = Color(0xFFEADDFF)
public val md_theme_dark_surface: Color = Color(0xFF24005A)
public val md_theme_dark_onSurface: Color = Color(0xFFEADDFF)
public val md_theme_dark_surfaceVariant: Color = Color(0xFF46464F)
public val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC6C5D0)
public val md_theme_dark_outline: Color = Color(0xFF90909A)
public val md_theme_dark_inverseOnSurface: Color = Color(0xFF24005A)
public val md_theme_dark_inverseSurface: Color = Color(0xFFEADDFF)
public val md_theme_dark_inversePrimary: Color = Color(0xFF4356B9)
public val md_theme_dark_shadow: Color = Color(0xFF000000)
public val md_theme_dark_surfaceTint: Color = Color(0xFFBAC3FF)
public val md_theme_dark_outlineVariant: Color = Color(0xFF46464F)
public val md_theme_dark_scrim: Color = Color(0xFF000000)

public val seed: Color = Color(0xFF3D50B3)
