# https://github.com/saveourtool/diktat/blob/master/diktat-rules/src/main/resources/diktat-analysis.yml
- name: DIKTAT_COMMON
  configuration:
    domainName: ru.pixnews
    testDirs: test
    disabledChapters: ""
    kotlinVersion: 1.8
    srcDirectories: "main"
- name: COMMENTED_BY_KDOC
  enabled: false
- name: CLASS_SHOULD_NOT_BE_ABSTRACT
  enabled: false
- name: CUSTOM_GETTERS_SETTERS
  enabled: false
- name: FILE_NO_BLANK_LINE_BETWEEN_BLOCKS
  enabled: true
- name: FILE_UNORDERED_IMPORTS
  enabled: false
  configuration:
    useRecommendedImportsOrder: false
- name: FUNCTION_NAME_INCORRECT_CASE
  enabled: false
- name: HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE
  enabled: false
- name: HEADER_MISSING_OR_WRONG_COPYRIGHT
  enabled: false
  configuration:
    isCopyrightMandatory: false
    copyrightText: ''
- name: HEADER_WRONG_FORMAT
  enabled: false
- name: LONG_NUMERICAL_VALUES_SEPARATED
  enabled: true
  configuration:
    maxNumberLength: '8'
- name: MAGIC_NUMBER
  enabled: false
- name: MISSING_KDOC_CLASS_ELEMENTS
  enabled: false
- name: MISSING_KDOC_ON_FUNCTION
  enabled: false
- name: MISSING_KDOC_TOP_LEVEL
  enabled: false
- name: RUN_IN_SCRIPT
  enabled: false
- name: TOO_LONG_FUNCTION
  enabled: false
- name: TRAILING_COMMA
  enabled: true
  configuration:
    valueArgument: true
    valueParameter: true
    indices: true
    whenConditions: true
    collectionLiteral: true
    typeArgument: true
    typeParameter: true
    destructuringDeclaration: true
- name: TYPE_ALIAS
  enabled: true
  configuration:
    typeReferenceLength: '35'
- name: VARIABLE_NAME_INCORRECT_FORMAT
  enabled: false
- name: WRONG_INDENTATION
  enabled: true
- name: WRONG_NEWLINES
  enabled: false
  configuration:
    maxParametersInOneLine: 2
    maxCallsInOneLine: 3
- name: WRONG_NEWLINES_AROUND_KDOC
  enabled: false
