/*
 * Copyright (c) 2023, the Pixnews project authors and contributors. Please see the AUTHORS file for details.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
 */

package ru.pixnews.feature.calendar.datasource.igdb.field.scheme

import ru.pixnews.igdbclient.model.Game

public enum class IgdbGameField(
    override val igdbName: String,
) : IgdbField<Game> {
    ID("id"),
    AGE_RATINGS("age_ratings"),
    AGGREGATED_RATING("aggregated_rating"),
    AGGREGATED_RATING_COUNT("aggregated_rating_count"),
    ALTERNATIVE_NAMES("alternative_names"),
    ARTWORKS("artworks"),
    BUNDLES("bundles"),
    CATEGORY("category"),
    COLLECTION("collection"),
    COVER("cover"),
    CREATED_AT("created_at"),
    DSLCS("dlcs"),
    EXPANSIONS("expansions"),
    EXTERNAL_GAMES("external_games"),
    FIRST_RELEASE_DATE("first_release_date"),
    FOLLOWS("follows"),
    FRANCHISE("franchise"),
    FRANCHISES("franchises"),
    GAME_ENGINES("game_engines"),
    GAME_MODES("game_modes"),
    GENRES("genres"),
    HYPES("hypes"),
    INVOLVED_COMPANIES("involved_companies"),
    KEYWORDS("keywords"),
    MULTIPLAYER_MODES("multiplayer_modes"),
    NAME("name"),
    PARENT_GAME("parent_game"),
    PLATFORMS("platforms"),
    PLAYER_PERSPECTIVES("player_perspectives"),
    RATING("rating"),
    RATING_COUNT("rating_count"),
    RELEASE_DATES("release_dates"),
    SCREENSHOTS("screenshots"),
    SIMILAR_GAMES("similar_games"),
    SLUG("slug"),
    STANDALONE_EXPANSIONS("standalone_expansions"),
    STATUS("status"),
    STORYLINE("storyline"),
    SUMMARY("summary"),
    TAGS("tags"),
    THEMES("themes"),
    TOTAL_RATING("total_rating"),
    TOTAL_RATING_COUNT("total_rating_count"),
    UPDATED_AT("updated_at"),
    URL("url"),
    VERSION_PARENT("version_parent"),
    VERSION_TITLE("version_title"),
    VIDEOS("videos"),
    WEBSITES("websites"),
    CHECKSUM("checksum"),
    REMAKES("remakes"),
    REMASTERS("remasters"),
    EXPANDED_GAMES("expanded_games"),
    PORTS("ports"),
    FORKS("forks"),
    LANGUAGE_SUPPORTS("language_supports"),
    GAME_LOCALIZATIONS("game_localizations"),
}
