name: Generate Baseline profile

on:
  workflow_dispatch:

env:
  CI: true
  TERM: dumb
  GRADLE_OPTS: >-
    -Dorg.gradle.jvmargs="-Xmx1536M -XX:MaxMetaspaceSize=1g -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC"
    -Dorg.gradle.workers.max=2
    -Dorg.gradle.vfs.watch=false
    -Dorg.gradle.dependency.verification.console=verbose
    -DwarningsAsErrors=false
  KOTLIN_DAEMON_JVMARGS: >-
    -Xmx1536M -XX:MaxMetaspaceSize=320M -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC -XX:NewRatio=1

jobs:
  baseline-profile:
    name: Generate baseline profile
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Clean the repository
        run: |
          /usr/bin/git clean -ffd || true
          /usr/bin/git reset --hard HEAD || true

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          clean: false
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Unpack google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" | base64 -d | zstd -d  -o app/src/google-services.json

      - name: Build dependencies, clean unused managed devices
        run: >
          ./gradlew
          -Pkotlin.daemon.jvmargs="${{ env.KOTLIN_DAEMON_JVMARGS }}"
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
          -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
          :test:benchmark:assembleBenchmark :app:assembleBenchmark
          cleanManagedDevices --unused-only
          --continue

      - name: Generate baseline profile
        run: >
          ./gradlew
          -Pkotlin.daemon.jvmargs="${{ env.KOTLIN_DAEMON_JVMARGS }}"
          -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
          -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
          :test:benchmark:pixel2api30BenchmarkAndroidTest
          --continue

      - name: Cleanup secrets
        if: ${{ always() }}
        run: rm -f app/src/google-services.json

      - name: Pack baseline profile
        run: >-
          tar -c -I 'zstd -19 -T0' -f baseline-profile.tar.zst test/benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/

      - name: Upload baseline profile
        uses: actions/upload-artifact@v3
        with:
          name: instrumented-test-reports
          path: baseline-profile.tar.zst

      - name: Replace old baseline profile
        run: >-
          cp test/benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/pixel5api33/*-baseline-prof.txt
          app/src/main/baseline-prof.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: app/src/main/baseline-prof.txt
          commit-message: "[baseline-profile-generator] New baseline profile"
          title: Updated baseline profile
          branch: auto/baseline-profile
