name: Generate Baseline profile

on:
  workflow_dispatch:

env:
  CI: true
  TERM: dumb
  GRADLE_OPTS: >-
    -Dorg.gradle.jvmargs="-Xmx1536M -XX:MaxMetaspaceSize=1g -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC"
    -Dorg.gradle.workers.max=2
    -Dorg.gradle.vfs.watch=false
    -Dorg.gradle.dependency.verification.console=verbose
    -DwarningsAsErrors=false
  KOTLIN_DAEMON_JVMARGS: >-
    -Xmx1536M -XX:MaxMetaspaceSize=320M -XX:SoftRefLRUPolicyMSPerMB=10 -XX:+UseParallelGC -XX:NewRatio=1

jobs:
  baseline-profile:
    name: Generate baseline profile
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Clean the repository
        run: |
          /usr/bin/git clean -ffd || true
          /usr/bin/git reset --hard HEAD || true

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Unpack pixnews.properties
        env:
          PIXNEWS_CONFIG: ${{ secrets.PIXNEWS_CONFIG }}
        run: echo "$PIXNEWS_CONFIG" | base64 -d | zstd -d  -o config/pixnews.properties

      - name: Generate baseline profile
        run: >
          ./gradlew
          -Pkotlin.daemon.jvmargs="${{ env.KOTLIN_DAEMON_JVMARGS }}"
          -Dorg.gradle.workers.max=1
          -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
          -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
          :test:benchmark:pixel2api30BenchmarkAndroidTest
          --scan --continue

      - name: Cleanup secrets
        if: ${{ always() }}
        run: rm -f config/pixnews.properties

      - name: Pack baseline profile
        run: >-
          tar -c -I 'zstd -19 -T0' -f baseline-profile.tar.zst test/benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/

      - name: Upload baseline profile
        uses: actions/upload-artifact@v4
        with:
          name: baseline-profile
          path: baseline-profile.tar.zst

      - name: Replace old baseline profile
        run: >-
          cp test/benchmark/build/outputs/managed_device_android_test_additional_output/benchmark/pixel5api33/*-baseline-prof.txt
          app/src/main/baseline-prof.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: app/src/main/baseline-prof.txt
          commit-message: "[baseline-profile-generator] New baseline profile"
          title: Updated baseline profile
          branch: auto/baseline-profile
