name: submit-dependency-snapshot

on:
  workflow_run:
    workflows: ['CI on push to main']
    types: [completed]

jobs:
  submit-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve dependency graph artifact and submit
        uses: gradle/gradle-build-action@v3
        with:
          dependency-graph: download-and-submit
